/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bfds.supoja;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        Solution s = new Solution();

        int[] answers = 
            // {1,2,3,4,5,1,2,3,4};
            {1,3,2,4,2};

        System.out.println(Arrays.toString(s.solution(answers)));
        
    }
}
